[package]
name = "zfi-macros"
description = "Macros to be used with zfi crate"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/ultimicro/zfi"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
